apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: drmf4jnnk-go 
  janus-idp.io/tekton: drmf4jnnk-go
  backstage.io/kubernetes-id: drmf4jnnk-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: drmf4jnnk-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  