apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: drmf4jnnk-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: drmf4jnnk-go 
  name: drmf4jnnk-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: drmf4jnnk-go 
